DATASET:
  root_dataset: "data/"
  list_train: ["./data/agri-debug.odgt", "./data/agri-debug-aug-planter_skip.odgt"]
  list_val: "./data/agri-debug.odgt"
  num_class: 7
  imgSizes: (300, 375, 450, 525, 600)
  # train_channels: 'rgb'
  # val_channels: ['nir3', 'rgb']
  shift_limit: (-1.0, 1.0)
  scale_limit: (-1.0, 1.0)
  aspect_limit: (-1.0, 1.0)
  hue_shift_limit: (-5, 5)
  sat_shift_limit: (-5, 5)
  val_shift_limit: (-10, 10)
  # shift_limit: (-0.0, 0.0)
  # scale_limit: (-0.0, 0.0)
  # aspect_limit: (-0.0, 0.0)

MODEL:
  arch: "Dinknet"
  backbone: "resnet101"
  ibn_mode: "none"
  # os: 16
  # num_low_level_feat: 3
  # interpolate_before_lastconv: True

LOSS:
  bce: 0.2
  dice: 1.
  lovasz: 1.

TRAIN:
  batch_size_per_gpu: 2
  iter_warmup: 150
  iter_static: 200
  iter_decay: 300
  start_epoch: 0
  optim: "SGD"
  lr: 0.01
  lr_pow: 0.5
  beta1: 0.9
  weight_decay: 5e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 12
  disp_iter: 20
  seed: 304

VAL:
  batch_size_per_gpu: 2
  visualize: False
  checkpoint: "epoch_40.pth"

TEST:
  checkpoint: "epoch_40.pth"
  result: "./"

DIR: "ckpt/"
